name: continuous-integration-example

on:
    push:
        branches:
            - main

jobs:
    build:
      # runs-on: ubuntu-latest
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v1
            - name: Set up JDK 1.8 so that I can run Java
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Change wrapper permissions
              run: chmod +x ./gradlew

            - name: Build with Gradle!
              working-directory: .
              run: ./gradlew build -x test

            - name: Run tests, please!
              working-directory: .
              run: ./gradlew test

    system-test:
#      runs-on: ubuntu-latest
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v1

        # Run the server
        - name: Run Docker Compose
          working-directory: .
          run: docker-compose up -d --build

        - uses: actions/setup-python@v1
          with:
            python-version: '3.7'
        - run: pip install pytest requests

        - name: Run system tests
          working-directory: .
          run: python3 -m pytest

        - name: Bring server down
          working-directory: .
          run: docker-compose down

    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@master

        - name: Copy repo to cloud
          uses: appleboy/scp-action@master
          env:
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            PORT: ${{ secrets.PORT }}
            KEY: ${{ secrets.KEY }}
          with:
            source: "./"
            target: "~/prod"

